In [1]:
import numpy as np
import pandas as pd
import pandas as pd
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
from sklearn.kernel_approximation import RBFSampler
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error)
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error, roc_curve, classification_report,auc)

In [7]:
traindata=pd.read_csv("tamil_featuresrun.csv",sep=",")

In [8]:
traindata

,MEAN OF STE,MEAN OF ZC,VARIANCE OF STE,VARIANCE OF ZC,Q(STE) AT 25%,Q(STE) AT 50%,Q(STE) AT 75%,Q(STE) AT 100%,Q(ZC) AT 25%,Q(ZC) AT 50%,Q(ZC) AT 75%,Q(ZC) AT 100%,LABEL
0,56.895570,121.041667,1024.885014,4865.259058,32.687867,46.262718,64.757551,86.366385,72.7,86.2,101.5,172.7,0
1,77.916430,126.343750,4857.843575,4239.200605,6.957925,46.643447,87.107018,140.909094,81.8,102.5,115.9,160.5,0
2,72.668716,111.718750,3688.563317,2395.563508,2.183770,54.213773,94.386656,128.489418,75.9,91.6,106.0,147.8,0
3,60.858265,137.718750,3530.393157,7242.789315,1.753526,32.360519,59.239536,120.374040,82.9,100.6,123.4,160.5,0
4,61.475705,131.312500,3689.357891,7430.931452,2.700385,33.664051,65.254070,104.824666,78.0,93.9,107.4,154.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,83.935066,99.928571,14170.574800,243.148352,1.380964,13.619231,42.331397,164.462747,89.3,92.1,95.0,112.2,10
506,45.341427,105.142857,3696.469001,1642.901099,1.281045,4.332670,26.048895,110.525633,84.3,87.0,92.4,127.6,10
507,78.828243,104.928571,13608.115290,496.225275,1.965257,15.073270,29.462583,157.275791,90.3,93.0,95.8,124.3,10
508,50.442477,104.714286,3206.624004,552.835165,1.892284,16.495271,53.879445,83.377937,92.3,94.3,99.9,108.9,10
509,49.732900,95.500000,4825.191198,436.730769,2.005879,11.316202,25.291831,96.384292,83.3,92.1,95.8,104.6,10

In [9]:
testdata=pd.read_csv("tamil_featuresrun.csv",sep=",")

In [10]:
testdata

,MEAN OF STE,MEAN OF ZC,VARIANCE OF STE,VARIANCE OF ZC,Q(STE) AT 25%,Q(STE) AT 50%,Q(STE) AT 75%,Q(STE) AT 100%,Q(ZC) AT 25%,Q(ZC) AT 50%,Q(ZC) AT 75%,Q(ZC) AT 100%,LABEL
0,56.895570,121.041667,1024.885014,4865.259058,32.687867,46.262718,64.757551,86.366385,72.7,86.2,101.5,172.7,0
1,77.916430,126.343750,4857.843575,4239.200605,6.957925,46.643447,87.107018,140.909094,81.8,102.5,115.9,160.5,0
2,72.668716,111.718750,3688.563317,2395.563508,2.183770,54.213773,94.386656,128.489418,75.9,91.6,106.0,147.8,0
3,60.858265,137.718750,3530.393157,7242.789315,1.753526,32.360519,59.239536,120.374040,82.9,100.6,123.4,160.5,0
4,61.475705,131.312500,3689.357891,7430.931452,2.700385,33.664051,65.254070,104.824666,78.0,93.9,107.4,154.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,83.935066,99.928571,14170.574800,243.148352,1.380964,13.619231,42.331397,164.462747,89.3,92.1,95.0,112.2,10
506,45.341427,105.142857,3696.469001,1642.901099,1.281045,4.332670,26.048895,110.525633,84.3,87.0,92.4,127.6,10
507,78.828243,104.928571,13608.115290,496.225275,1.965257,15.073270,29.462583,157.275791,90.3,93.0,95.8,124.3,10
508,50.442477,104.714286,3206.624004,552.835165,1.892284,16.495271,53.879445,83.377937,92.3,94.3,99.9,108.9,10
509,49.732900,95.500000,4825.191198,436.730769,2.005879,11.316202,25.291831,96.384292,83.3,92.1,95.8,104.6,10

In [11]:
X = traindata.iloc[:,1:91]
Y = traindata.iloc[:,0]
C = testdata.iloc[:,0]
T = testdata.iloc[:,1:91]

In [12]:
scaler = Normalizer().fit(X)
trainX = scaler.transform(X)

In [13]:
scaler = Normalizer().fit(X)
trainX = scaler.transform(X)

In [14]:
scaler = Normalizer().fit(T)
testT = scaler.transform(T)

In [15]:
traindata = np.array(trainX)
trainlabel = np.array(Y)

In [16]:
model = KNeighborsClassifier()
model.fit(traindata, trainlabel)

ValueError: Unknown label type: 'continuous'